Repository AstroAccelerateOrg/astro-accelerate, pull requests merged in 2018-09, with the labels that each got.

#37 Cc 33 create pull request template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE/pull-request.md
Labels: Interfaces

#30 Update issue templates, add a bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Interfaces

#41 Expand .gitignore list
  .gitignore
Labels: Style

#43 Cc 42 rmimages
  doc/figures/BOXDIT_R-SNR_32_16_8_integrated.jpg
  doc/figures/MSD_plane_fake_w-wth_OR_with_s_wiki.jpg
  doc/figures/SPDT_P100_DM50_W62_SNRvar.jpg
  doc/figures/SPDT_P70_DM2100_W43_SNR8.jpg
  doc/figures/SPDT_P70_DM70_W43_SNR8.jpg
  doc/figures/SPDT_Wvar.jpg
Labels: Feature, Style

#45 Move developers_guide.md up to root directory of repository, renamed …
  CONTRIBUTING.md
Labels: Documentation, Style

#47 Update CONTRIBUTING.md with markdown
  CONTRIBUTING.md
Labels: Documentation, Style

#39 Cc 38 readmemarkdown
  README
  README.md
Labels: Documentation, Style

#55 Remove test.dat from repository.
  test.dat
Labels: Feature, Style

#60 Cc 53 setupscript
  README.md
  bootstrap.sh
  setup.sh
Labels: Documentation, Feature, Interfaces, Style

#89 Starting the memory allocation of MSD only if it is requested.
  lib/host_main_function.cu
Labels: Bug

#95 Cc device constant
  include/device_dedispersion_kernel.hpp
  src/device_dedispersion_kernel.cu
  src/device_load_data.cu
Labels: Bug
