Repository AstroAccelerateOrg/astro-accelerate, pull requests merged in 2018-11, with the labels that each got.

#122 Jn 119 zerodm kernel
  include/device_zero_dm_kernel.hpp
  src/device_zero_dm.cu
  src/device_zero_dm_kernel.cu
Labels: Performance

#124 correction of passing the correct value to MSD_DIT_size
  src/device_MSD_plane_profile.cu
Labels: Bug

#120 Faster way of getting number of samples from fil file
  src/host_get_file_data.cu
Labels: Feature, Performance

#128 Create .gitlab-ci.yml
  .gitlab-ci.yml
Labels: Feature, Validation

#129 Remove test from yml
  .gitlab-ci.yml
Labels: Feature, Validation

#130 Remove test implementation from yml
  .gitlab-ci.yml
Labels: Feature, Validation

#131 Change tag to astraios
  .gitlab-ci.yml
Labels: Feature, Validation

#133 Clarify README.md
  README.md
Labels: Documentation
