Repository AstroAccelerateOrg/astro-accelerate, pull requests merged in 2018-10, with the labels that each got.

#102 Cc 101 CONTRIBUTING guidelines
  CONTRIBUTING.md
Labels: Documentation

#99 [WIP] Merge cc_93_sps into cc_93_ddtr
  include/FilterBankDataMeta.hpp
  include/device_MSD_parameters.hpp
  include/device_SPS_DataDescription.hpp
  include/device_SPS_parameters.hpp
  include/device_SPS_plan.hpp
  include/device_SPS_search.hpp
  include/device_SPS_strategy.hpp
  include/device_analysis.hpp
  src/device_analysis.cu
  src/host_main_function.cu
Labels: Interfaces

#107 README.md to mention correct executable name
  README.md
Labels: Documentation

#109 Added performance optimisation issue template
  .github/ISSUE_TEMPLATE/performance-optimisation.md
Labels: Feature

#116 Cc compilerwarnings
  include/device_MSD_shared_kernel_functions.cuh
  include/device_cuda_deprecated_wrappers.cuh
  input_files/ska_test_file.txt
  src/dcdflib.cpp
  src/device_MSD_outlier_rejection_kernel.cu
  src/device_MSD_plane_profile.cu
  src/device_SPS_inplace_kernel.cu
  src/device_analysis.cu
  src/device_periods.cu
  src/device_threshold_kernel.cu
  src/fdas_device.cu
  src/fdas_host.cu
  src/host_MSD_stratagy.cu
  src/host_export.cu
  src/host_get_file_data.cu
  src/host_get_recorded_data.cu
  src/host_stratagy.cu
  src/main.cpp
  src/presto_funcs.cpp
Labels: Feature

#113 Cc 93 sps
  .vscode/settings.json
  include/FilterBankDataMeta.hpp
  include/device_SPS_long.hpp
  include/device_SPS_plan.hpp
  include/device_SPS_search.hpp
  include/device_analysis.hpp
  include/device_peak_find.hpp
  include/device_threshold.hpp
  src/device_SPS_long.cu
  src/device_SPS_long_kernel.cu
  src/device_analysis.cu
  src/device_peak_find.cu
  src/device_peak_find_kernel.cu
  src/device_threshold.cu
  src/device_threshold_kernel.cu
  src/host_main_function.cu
Labels: Interfaces
