Repository AstroAccelerateOrg/astro-accelerate, pull requests merged in 2019-03, with the labels that each got.

#166 Corrected back ticks for quote and file name
  wiki/fourier_domain_acceleration_search.md
Labels: Documentation

#164 Correcting documentation on FDAS
  wiki/fourier_domain_acceleration_search.md
Labels: Documentation

#169 Standalone code exits if card_init fails. card_init now loops over a …
  cmake/version.h.in
  include/aa_device_info.hpp
  src/aa_main.cpp
Labels: Bug

#170 Removed double notice
  include/aa_pipeline_api.hpp
Labels: Bug

#171 Added aa_version.hpp so that compilation with the Makefile works agai…
  CMakeLists.txt
  include/aa_device_info.hpp
Labels: Feature

#174 Fix for #define for compilation using makefile only
  include/aa_device_info.hpp
Labels: Bug, Feature

#175 Update minimum CMake to 3.9.0
  CMakeLists.txt
Labels: Interfaces

#176 Create .clang-format
  .clang-format
Labels: Style

#177 Fix printf warnings for debug mode.
  src/aa_device_MSD_plane_profile.cu
Labels: Bug
